version: "3"

services:
  timestrap:
    container_name: timestrap
    image: iwilltry42/timestrap:20200701.2
    command: daphne timestrap.asgi:application --port 8899 --bind 0.0.0.0 -v2
    ports:
      - "8899:8899"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=timestrap.settings.docker
      - SECRET_KEY=super-secret-key
      - POSTGRES_DB=timestrap
      - POSTGRES_USER=timestrap
      - POSTGRES_PASSWORD=timestrap
    networks:
      - timestrap_network
      - web

  db:
    image: postgres
    container_name: timestrap_postgres
    environment:
      - POSTGRES_DB=timestrap
      - POSTGRES_USER=timestrap
      - POSTGRES_PASSWORD=timestrap
      - PGDATA=/db-data
    volumes:
      - ./data:/db-data
    networks:
      - timestrap_network

  redis:
    image: redis
    container_name: timestrap_redis
    networks:
      - timestrap_network

networks:
  timestrap_network:
    external: false
  web:
    external: true